name: Release CodeBook
on:
  release:
    types: [published]

env:
  SWIFT_VERSION: "5.9.1"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/${{ github.repository }}

      - name: lowercase github.repository
        run: |
          echo "lc_repository=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          file: deployment/Dockerfile
          push: true
          build-args: |
            SWIFT_VERSION=${{ env.SWIFT_VERSION }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ env.lc_repository }}:latest
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

